// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                      pgtype.UUID
	Username                string
	Email                   string
	Phone                   pgtype.Text
	Status                  string
	PreferenceLowChannel    string
	PreferenceMediumChannel string
	PreferenceHighChannel   string
}
