// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id, 
    username, 
    email, 
    phone, 
    status, 
    preference_low_channel, 
    preference_medium_channel, 
    preference_high_channel 
FROM 
    users 
WHERE 
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.PreferenceLowChannel,
		&i.PreferenceMediumChannel,
		&i.PreferenceHighChannel,
	)
	return i, err
}
